<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>enc</string>
	</array>

	<key>name</key>
	<string>Enceladus</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.builtin.enceladus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(print|println|die|assert|dict|set)\b</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(import|let|var|match)\b</string>
			<key>name</key>
			<string>keyword.other.enceladus</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(and|or|in|to|til|as|where)\b</string>
			<key>name</key>
			<string>keyword.other.enceladus</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(do|if|then|else|while|for|return|break|forever|elif|pass|continue)\b</string>
			<key>name</key>
			<string>keyword.control.enceladus</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b[0-9]+(i|u|u8)?\b</string>
			<key>name</key>
			<string>constant.numeric.enceladus</string>
		</dict>

		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.enceladus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.enceladus</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.enceladus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[nrt\\]</string>
					<key>name</key>
					<string>constant.character.escape.enceladus</string>
				</dict>
			</array>
		</dict>

		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.enceladus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.enceladus</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>

		<dict>
			<key>match</key>
			<string>^\s*\b(def)\b\s*([a-z][a-zA-Z0-9.']*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.enceladus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.enceladus</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>match</key>
			<string>^(foreign|builtin)\s*([a-z][a-zA-Z0-9.']*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.enceladus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.enceladus</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>match</key>
			<string>^\s*\b(struct|enum|trait|type)\b\s*([a-zA-Z][a-zA-Z0-9.']*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.enceladus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.enceladus</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>match</key>
			<string>^\s*\b(impl)\b</string>
			<key>name</key>
			<string>storage.type.enceladus</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b[A-Z]\w*\b</string>
			<key>name</key>
			<string>constant.other.enceladus</string>
		</dict>

		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>

		<dict>
			<key>include</key>
			<string>#infix_op</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(\+|-|\*|/|%|&gt;|&lt;|:|=|:=|\$|\||->|&gt;=|==|!=|::|\+=|-=|\*=|\/=|%=)</string>
			<key>name</key>
			<string>keyword.operator.enceladus</string>
		</dict>

		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>punctuation.separator.comma.enceladus</string>
		</dict>
	</array>

	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.enceladus</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.enceladus</string>
				</dict>
			</array>
		</dict>
	</dict>

	<key>scopeName</key>
	<string>source.enceladus</string>

	<key>uuid</key>
	<string>7C1FA7A0-BF5D-4F23-B8ED-44B4DE14B835</string>
</dict>
</plist>
