#!/bin/bash
set -e

build/src/simplec testing/$1.enc > build/$1.asm

if [[ $(uname) == "Darwin" ]]; then
    nasm -fmacho64 build/$1.asm -o build/$1.o
    nasm -fmacho64 lib/gc.asm -d__APPLE__ -o build/gc.o

    gcc -O2 -c lib/library.c -o build/library.o -O -DNDEBUG
    gcc -m64 -Wl,-no_pie build/$1.o build/library.o build/gc.o -o build/$1

else
    nasm -felf64 build/$1.asm -o build/$1.o
    nasm -felf64 lib/gc.asm -o build/gc.o

    gcc -O2 -std=gnu99 -g -c lib/library.c -o build/library.o
    gcc build/$1.o build/library.o build/gc.o -o build/$1
fi
