bits 64
section .text
global initGC, _walkStack, stackBottom
extern __walkStackC, __globalVarTable

initGC:
    mov rax, rsp
    add rax, 8
    mov qword [rel stackBottom], rax
    ret

_walkStack:
    push rbp
    mov rbp, rsp

    ; Get top of stack before the call to this function
    mov rdi, rbp
    add rdi, 16

    ; Get bottom of stack at the beginning of the program
    mov rsi, qword [rel stackBottom]

    ; Table of global variables generated by the compiler
    mov rdx, __globalVarTable

    mov r15, rsp
    and rsp, -16
    add rsp, -8
    push r15
    call __walkStackC
    pop rsp

    pop rbp
    ret

section .data
stackBottom:
    dq 0
